language: cpp

compiler:
    - gcc

dist: trusty
sudo: false

addons:
  apt:
    sources:
    packages:
      - qt5-default
      - libopencv-dev

before_srcipt:
    - mkdir build
    - cd build
    - mkdir clang
    - cd gcc
    - cmake ../.. 

script: 
    - cd build/gcc
    - make test
