
language: cpp

sudo: false

compiler:
  - gcc

dist: trusty

addons:
  apt:
    packages:
      - qt5-default
      - libopencv-dev

install:
  - gcc-5 --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build-gcc
  - cd build-gcc
  - cmake ..
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cd build-gcc
  - make
