dist: trusty

# to avoid exporting gcc4.8
language: none

sudo: required

compiler:
  - gcc

branches:
  only:
  - master
  - testing
  - travis-ci-test

arch:
  packages:
    - wget
    - gcc
    - cmake
    - ninja
    - qt5-base
    - opencv
  script:
   # Installing lcov
   - cd ${HOME}
   - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
   - tar xf lcov_1.13.orig.tar.gz
   - cd lcov-1.13/
   - sudo make install
   # Run build
   - ./run_build.sh

before_install:
    - export SOURCE_DIR=${TRAVIS_BUILD_DIR}
    - export BUILD_DIR=${TRAVIS_BUILD_DIR}/build
    - export GENERATE_COVERAGE=true
    - export UPLOAD_COVERAGE=true

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

notifications:
  email:
    - Bastian.Schumacher@gmx.de

env:
  global:
  - LANG="en_US.UTF-8"
