dist: trusty

# to avoid exporting gcc4.8
language: none

sudo: required

compiler:
  - gcc

branches:
  only:
  - master
  - testing
  - travis-ci-test

arch:
  packages:
    - gcc
    - cmake
    - ninja
    - kcov
    - qt5-base
    - opencv
  script: ./run_build.sh

before_install:
    - export SOURCE_DIR=${TRAVIS_BUILD_DIR}
    - export BUILD_DIR=${TRAVIS_BUILD_DIR}/build
    - export GENERATE_COVERAGE=true
    - export UPLOAD_COVERAGE=true

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

notifications:
  email:
    - Bastian.Schumacher@gmx.de

env:
  global:
  - LANG="en_US.UTF-8"
