
language: cpp

sudo: required

compiler:
  - gcc

branches:
  only:
  - master
  - testing
  - travis-ci-test

arch:
  packages:
    - gcc-5
    - g++-5
    - cmake
    - ninja-build
    - lcov
    - qt5-default
    - libopencv-dev
  script: ./run_build.sh

before_install:
    - export SOURCE_DIR=${TRAVIS_BUILD_DIR}
    - export BUILD_DIR=${TRAVIS_BUILD_DIR}/build

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --remove coverage.info 'moc_*' --output-file coverage.info # filter out generated code
  - lcov --remove coverage.info 'catch.hpp' --output-file coverage.info # filter out catch library
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

notifications:
  email:
    - Bastian.Schumacher@gmx.de

env:
  global:
  - LANG="en_US.UTF-8"
