dist: trusty

language: cpp

sudo: required

compiler:
  - gcc

branches:
  only:
  - master
  - testing
  - travis-ci-test

arch:
  packages:
    - gcc
    - cmake
    - ninja
    - kcov
    - qt5-base
    - opencv
  script: ./run_build.sh

before_install:
    - export SOURCE_DIR=${TRAVIS_BUILD_DIR}
    - export BUILD_DIR=${TRAVIS_BUILD_DIR}/build

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - kcov --exclude-path=/usr/ --exclude-pattern=moc_ . bin/tests
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

notifications:
  email:
    - Bastian.Schumacher@gmx.de

env:
  global:
  - LANG="en_US.UTF-8"
