
language: cpp
sudo: false

compiler:
  - gcc

sudo: false

addons:
  apt:
    sources:
    packages:
      - qt5-default
      - libopencv-dev

bevore_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build-gcc
  - cd build-gcc
  - cmake ..
  - cd ${TRAVIS_BUILD_DIR}

srcipt:
  - cd build-gcc
  - make
  - make test
