
language: cpp

sudo: required

services:
  - docker

compiler:
  - gcc

addons:
  apt:
    packages:
      - gcc-5
      - g++-5
      - qt5-default
      - libopencv-dev
    sources:
      - ubuntu-toolchain-r-test

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build-gcc && mkdir build-gcc-coverage
  - cd ${TRAVIS_BUILD_DIR}/build-gcc
  - cmake -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_BUILD_TYPE=Release ..
  - cd ${TRAVIS_BUILD_DIR}/build-gcc-coverage
  - cmake -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_BUILD_TYPE=Debug -DGENERATE_COVERAGE=ON ..

script:
  - cd ${TRAVIS_BUILD_DIR}/build-gcc
  - make
  - make test

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build-gcc-coverage
  - make Soda_TestCoverage
  - bash <(curl -s https://codecov.io/bash)
