language: cpp

compiler:
    - gcc

dist: trusty
sudo: false

addons:
  apt:
    sources:
    packages:
      - qt5-default
      - libopencv-dev

before_srcipt:
    - mkdir -p build/gcc
    - cd gcc
    - cmake ../..
    - cd ${TRAVIS_BUILD_DIR}

script: 
    - cd build/gcc
    - make test
