
language: cpp

sudo: false

compiler:
  - gcc

dist: trusty

install:
  - qt5-default
  - libopencv-dev

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build-gcc
  - cd build-gcc
  - cmake ..
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cd build-gcc
  - make test
