
language: cpp

sudo: required

compiler:
  - gcc

dist: trusty

install:
  - sudo apt-get install -qq g++-5
  - sudo apt-get install -qq qt5-default
  - sudo apt-get install -qq libopencv-dev

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build-gcc
  - cd build-gcc
  - cmake ..
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cd build-gcc
  - make
